<a href="https://colab.research.google.com/github/Likhithluck/Capstone-Project/blob/tarun/Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (4.11.0.86)
Requirement already satisfied: numpy>=1.21.2 in /usr/local/lib/python3.11/dist-packages (from opencv-python) (2.0.2)

In [ ]:
!pip install pdf2image
!pip install datasets
!pip install pytesseract
!pip install pdfplumber
!apt-get install tesseract-ocr
!apt-get install libtesseract-dev
!apt-get install poppler-utils
!pip install opencv-python

Collecting pdf2image
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from pdf2image) (11.1.0)
Downloading pdf2image-1.17.0-py3-none-any.whl (11 kB)
Installing collected packages: pdf2image
Successfully installed pdf2image-1.17.0
Collecting datasets
  Downloading datasets-3.4.1-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.14)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.29.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Downloading datasets-3.4.1-py3-none-any.whl (487 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 487.4/487.4 kB 8.3 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.7 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 14.1 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 14.0 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.4.1 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0
Collecting pytesseract
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (24.2)
Requirement already satisfied: Pillow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from pytesseract) (11.1.0)
Downloading pytesseract-0.3.13-py3-none-any.whl (14 kB)
Installing collected packages: pytesseract
Successfully installed pytesseract-0.3.13
Collecting pdfplumber
  Downloading pdfplumber-0.11.5-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.5/42.5 kB 1.9 MB/s eta 0:00:00
Collecting pdfminer.six==20231228 (from pdfplumber)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.1.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20231228->pdfplumber) (3.4.1)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20231228->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (2.22)
Downloading pdfplumber-0.11.5-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 4.1 MB/s eta 0:00:00
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 44.5 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 61.8 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20231228 pdfplumber-0.11.5 pypdfium2-4.30.1
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 29 not upgraded.
Need to get 4,816 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1.1 [1,591 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1.1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr amd64 4.1.1-2.1build1 [236 kB]
Fetched 4,816 kB in 0s (14.3 MB/s)
Selecting previously unselected package tesseract-ocr-eng.
(Reading database ... 126209 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-eng_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-eng (1:4.00~git30-7274cfa-1.1) ...
Selecting previously unselected package tesseract-ocr-osd.
Preparing to unpack .../tesseract-ocr-osd_1%3a4.00~git30-7274cfa-1.1_all.deb ...
Unpacking tesseract-ocr-osd (1:4.00~git30-7274cfa-1.1) ...
Selecting previously unselected package tesseract-ocr.
Preparing to unpack .../tesseract-ocr_4.1.1-2.1build1_amd64.deb ...
Unpacking tesseract-ocr (4.1.1-2.1build1) ...
Setting up tesseract-ocr-eng (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr-osd (1:4.00~git30-7274cfa-1.1) ...
Setting up tesseract-ocr (4.1.1-2.1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libarchive-dev libleptonica-dev
The following NEW packages will be installed:
  libarchive-dev libleptonica-dev libtesseract-dev
0 upgraded, 3 newly installed, 0 to remove and 29 not upgraded.
Need to get 3,743 kB of archives.
After this operation, 16.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libarchive-dev amd64 3.6.0-1ubuntu1.3 [581 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libleptonica-dev amd64 1.82.0-3build1 [1,562 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libtesseract-dev amd64 4.1.1-2.1build1 [1,600 kB]
Fetched 3,743 kB in 0s (12.8 MB/s)
Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 126256 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.6.0-1ubuntu1.3_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.6.0-1ubuntu1.3) ...
Selecting previously unselected package libleptonica-dev.
Preparing to unpack .../libleptonica-dev_1.82.0-3build1_amd64.deb ...
Unpacking libleptonica-dev (1.82.0-3build1) ...
Selecting previously unselected package libtesseract-dev:amd64.
Preparing to unpack .../libtesseract-dev_4.1.1-2.1build1_amd64.deb ...
Unpacking libtesseract-dev:amd64 (4.1.1-2.1build1) ...
Setting up libleptonica-dev (1.82.0-3build1) ...
Setting up libarchive-dev:amd64 (3.6.0-1ubuntu1.3) ...
Setting up libtesseract-dev:amd64 (4.1.1-2.1build1) ...
Processing triggers for man-db (2.10.2-1) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  poppler-utils
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 186 kB of archives.
After this operation, 696 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 poppler-utils amd64 22.02.0-2ubuntu0.6 [186 kB]
Fetched 186 kB in 0s (1,177 kB/s)
Selecting previously unselected package poppler-utils.
(Reading database ... 126389 files and directories currently installed.)
Preparing to unpack .../poppler-utils_22.02.0-2ubuntu0.6_amd64.deb ...
Unpacking poppler-utils (22.02.0-2ubuntu0.6) ...
Setting up poppler-utils (22.02.0-2ubuntu0.6) ...
Processing triggers for man-db (2.10.2-1) ...

In [ ]:
import pandas as panda
from huggingface_hub import login
from datasets import load_dataset
from google.colab import files
import numpy as np
import pytesseract
from pdf2image import convert_from_path
import pdfplumber
from google.colab import files
import spacy
import json
import cv2
import re
import json
from datetime import datetime
from transformers import  BartTokenizer, AutoModelForSeq2SeqLM,AutoTokenizer, BartForConditionalGeneration

pytesseract.pytesseract.tesseract_cmd = r'/usr/bin/tesseract'

In [ ]:
from google.colab import userdata
key=userdata.get('hugging_face_key12')

In [ ]:
login(token=key)

In [ ]:
# dataset1 = load_dataset('mychen76/invoices-and-receipts_ocr_v1')
# dataset2 = load_dataset('mychen76/invoices-and-receipts_ocr_v2')

In [ ]:
# #Basic OCR
# # Preprocessing Function
# def preprocess_image(image):
#     gray = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2GRAY)
#     denoised = cv2.fastNlMeansDenoising(gray, None, 30, 7, 21)
#     clahe = cv2.createCLAHE(clipLimit=5.0, tileGridSize=(8, 8))
#     contrast_enhanced = clahe.apply(denoised)
#     kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
#     cleaned = cv2.morphologyEx(contrast_enhanced, cv2.MORPH_CLOSE, kernel)
#     thresh = cv2.adaptiveThreshold(cleaned, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
#                                    cv2.THRESH_BINARY, 11, 2)
#     return thresh


# def extract_text_from_pdf(pdf_path):
#     images = convert_from_path(pdf_path, dpi=300 ,poppler_path="/usr/bin" )

#     extracted_text = ""

#     for i, image in enumerate(images):
#         processed_image = preprocess_image(image)
#         custom_config = '--psm 6 --oem 3'
#         page_text = pytesseract.image_to_string(processed_image, config=custom_config)
#         extracted_text += f"\n--- Page {i + 1} ---\n{page_text}"

#     print("Extracted Text:\n", extracted_text)


# #Dataset pdf
# pdf_path = "/content/invoice_Yana Sorensen_5434.pdf"
# #OCR extraction
# text=extract_text_from_pdf(pdf_path)
# print(text)

In [ ]:

# def extract_clean_text(pdf_path):
#     clean_text = ""
#     with pdfplumber.open(pdf_path) as pdf:
#         for page_num, page in enumerate(pdf.pages):
#             text = page.extract_text()
#             if text:
#                 clean_text += text.strip() + "\n\n"
#     print(clean_text)
#     with open("clean_text_output.txt", "w", encoding="utf-8") as file:
#         file.write(clean_text)

# # Path to PDF
# pdf_path = "/content/invoice_Yana Sorensen_5434.pdf"

# # Run Extraction
# ocr_pdf_plum=extract_clean_text(pdf_path)

In [ ]:
#upload file
def upload_pdfs():
    """Uploads multiple PDF files and returns a list of their paths."""
    uploaded = files.upload()
    pdf_paths = list(uploaded.keys())
    return pdf_paths

#preprocess the image
def preprocess_image(image):
    gray = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2GRAY)
    sharpened = cv2.filter2D(gray, -1, np.array([[0, -1, 0], [-1, 5, -1], [0, -1, 0]]))
    denoised = cv2.fastNlMeansDenoising(sharpened, None, 30, 7, 21)
    clahe = cv2.createCLAHE(clipLimit=5.0, tileGridSize=(8, 8))
    contrast_enhanced = clahe.apply(denoised)
    return contrast_enhanced


#OCR Extraction
def extract_text_with_ocr(pdf_path):
    extracted_text = ""
    images = convert_from_path(pdf_path, dpi=300, poppler_path="/usr/bin")

    for i, image in enumerate(images):
        processed_image = preprocess_image(image)
        custom_config = '--psm 3 --oem 3'
        page_text = pytesseract.image_to_string(processed_image, config=custom_config)
        extracted_text += f"--- Page {i + 1} ---\n{page_text.strip()}\n\n"

    return extracted_text

# Table Extraction Using pdfplumber
def extract_tables_from_pdf(pdf_path):
    table_data = ""

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages):

            # table settings
            tables = page.extract_tables(
                table_settings={
                    "snap_tolerance": 10,
                    "join_tolerance": 10,
                    "edge_min_length": 50,
                    "horizontal_strategy": "lines",
                    "vertical_strategy": "lines",
                }
            )


            if tables:
                table_data += f"\n--- Tables from Page {page_num + 1} ---\n"
                for table in tables:
                    for row in table:

                        cleaned_row = [str(cell).strip() if cell else '' for cell in row]
                        table_data += " | ".join(cleaned_row) + "\n"
            else:
                print("No table found on this page.")

    return table_data


def extract_data(pdf_path):
    print("(OCR)")
    ocr_text = extract_text_with_ocr(pdf_path)

    print("\nTables")
    table_data = extract_tables_from_pdf(pdf_path)

    return ocr_text, table_data


# #Testing
# pdf_path = "/content/invoice_Todd Sumrall_11844.pdf"
# #pdf_path=upload_pdf()
# ocr_text, table_data = extract_data(pdf_path)

# print("\nOCR Text\n")
# print(ocr_text)
# print(table_data)

In [ ]:


nlp = spacy.load("en_core_web_sm")

def perform_ner(text):
    doc = nlp(text)
    entities = []
    for ent in doc.ents:
        entities.append({
            "text": ent.text,
            "label": ent.label_,
            "start_char": ent.start_char,
            "end_char": ent.end_char
        })
    return entities

In [ ]:
def ocr_to_json_with_ner(ocr_text, ner_results):

    invoice_data = {
        "invoice_number": None,
        "date": None,
        "bill_to": None,
        "ship_to": None,
        "ship_mode": None,
        "balance_due": None,
        "items": [],
        "subtotal": None,
        "discount": None,
        "shipping": None,
        "total": None,
        "notes": "",
        "terms": {"order_id": None}
    }

    #Items
    item = []
    person_entities = [entity for entity in ner_results if entity["label"] == "PERSON"]
    date_entities = [entity for entity in ner_results if entity["label"] == "DATE"]
    invoice_entities = [entity for entity in ner_results if entity["label"] == "MONEY"]

    #bill_to
    if len(person_entities) >= 3:
        invoice_data["bill_to"] = person_entities[2]["text"]
    else:
        invoice_data["bill_to"] = None

    # INVOICE NUM
    invoice_pattern = r"(\#\s?\d{1,6})"
    invoice_number_match = re.search(invoice_pattern, ocr_text)

    if invoice_number_match:
        invoice_number = invoice_number_match.group(1).strip()
        invoice_data["invoice_number"] = invoice_number

    # Ship_to
    if invoice_data["bill_to"]:
        # Search for the bill_to value in the OCR text
        bill_to_index = ocr_text.find(invoice_data["bill_to"])
        if bill_to_index != -1:
            # Extract the text after the bill_to value
            text_after_bill_to = ocr_text[bill_to_index + len(invoice_data["bill_to"]):]
            # Find the text before "Balance Due"
            balance_due_index = text_after_bill_to.find("Balance Due")
            if balance_due_index != -1:
                # Extract the ship_to value (text between the comma after bill_to and "Balance Due")
                ship_to_value = text_after_bill_to[:balance_due_index].strip()
                ship_to_value = ship_to_value.strip(", ")
                ship_to_value = ship_to_value.replace(": ", "").replace("\n", " ")
                invoice_data["ship_to"] = ship_to_value

    # Ship_mode
    ship_mode_match = re.search(r"Ship Mode: ([\w\s]+)\n", ocr_text)
    if ship_mode_match:
        ship_mode = ship_mode_match.group(1).strip()
        invoice_data["ship_mode"] = ship_mode

    #Date
    date_pattern = r"(\b(?:[A-Za-z]{3,9}\s\d{1,2},?\s?\d{4}|\d{1,2}-[A-Za-z]{3}-\d{4}|\d{4}-\d{2}-\d{2})\b)"

    date_pattern_match = re.search(date_pattern, ocr_text)

    if date_pattern_match:
        extracted_date = date_pattern_match.group(1).strip()
        try:
            # Handling different date formats
            if "," in extracted_date:
                date_obj = datetime.strptime(extracted_date, "%b %d %Y")
            elif "-" in extracted_date:
                date_obj = datetime.strptime(extracted_date, "%d-%b-%Y") if len(extracted_date.split("-")[0]) == 2 else datetime.strptime(extracted_date, "%Y-%m-%d")
            else:
                date_obj = datetime.strptime(extracted_date, "%b %d %Y")

            #  standard format YYYY-MM-DD
            invoice_data["date"] = date_obj.strftime("%Y-%m-%d")

        except ValueError:
            invoice_data["date"] = None
    else:
        invoice_data["date"] = None

    # Balance_due
    balance_due_match = re.search(r"Balance Due: \$([\d,]+\.\d{2})", ocr_text)
    if balance_due_match:
        balance_due = balance_due_match.group(1).strip()
        invoice_data["balance_due"] = float(balance_due.replace(",", ""))

    # Subtotal
    subtotal_match = re.search(r"Subtotal: \$([\d,]+\.\d{2})", ocr_text)
    if subtotal_match:
      subtotal = subtotal_match.group(1).strip()
      invoice_data["subtotal"] = float(subtotal.replace(",", ""))

    #discount
    discount_match = re.search(r"Discount\s?\(?\d*%?\)?\s?:\s?\$([\d,]+\.\d{2})", ocr_text)
    if discount_match:
        discount = discount_match.group(1).strip()
        invoice_data["discount"] = float(discount.replace(",", ""))

    #Shipping
    shipping_match = re.search(r"Shipping: \$([\d,]+\.\d{2})", ocr_text)
    if shipping_match:
        shipping = shipping_match.group(1).strip()
        invoice_data["shipping"] = float(shipping.replace(",", ""))

    # Total
    total_match = re.search(r"Total: \$([\d,]+\.\d{2})", ocr_text)
    if total_match:
        total = total_match.group(1).strip()
        invoice_data["total"] = float(total.replace(",", ""))


    # Notes
    notes_match = re.search(r"Notes:\s*(.*?)\s*(?=Terms:|$)", ocr_text, re.DOTALL)
    if notes_match:
        notes = notes_match.group(1).strip()
        invoice_data["notes"] = notes

    # Order_ID
    order_id_match = re.search(r"Order ID : (\S+)", ocr_text)
    if order_id_match:
        order_id = order_id_match.group(1).strip()
        invoice_data["terms"]["order_id"] = order_id


    item_pattern = re.compile(r"([\w\s\-,]+)\s+(\d+)\s+\$([\d,]+\.\d{2})\s+\$([\d,]+\.\d{2})")
    matches = item_pattern.findall(ocr_text)

    for match in matches:
        item_name = match[0].strip()
        item_name = re.sub(r"Quantity Rate Amount\n", "", item_name).strip()
        item_name = re.sub(r"Amount\n", "", item_name).strip()
        quantity = int(match[1].strip())
        unit_price = float(match[2].replace(",", "").strip())
        total_price = float(match[3].replace(",", "").strip())

        # Add the item to the list
        item.append({
            "item_name": item_name,
            "quantity": quantity,
            "unit_price": unit_price,
            "total_price": total_price
        })
    #ITEMS
    invoice_data["items"] = item
    return invoice_data["ship_to"]
    # return json.dumps({"invoice": invoice_data}, indent=4)



# json_output = ocr_to_json_with_ner(ocr_text, ner_results)
# print(json_output)

In [ ]:
# multiple files
def handle_multiple_files():
    pdf_paths = upload_pdfs()
    all_ocr_texts = []
    all_table_data = []

    for pdf_path in pdf_paths:
        ocr_text, table_data = extract_data(pdf_path)

        all_ocr_texts.append(ocr_text)
        all_table_data.append(table_data)
    return all_ocr_texts, all_table_data


ocr_texts, tables = handle_multiple_files()

Saving invoice_Tony Molinari_25880.pdf to invoice_Tony Molinari_25880.pdf
Saving invoice_Tony Molinari_25881.pdf to invoice_Tony Molinari_25881.pdf
Saving invoice_Tracy Blumstein_20584.pdf to invoice_Tracy Blumstein_20584.pdf
Saving invoice_Tracy Blumstein_28215.pdf to invoice_Tracy Blumstein_28215.pdf
Saving invoice_Tracy Hopkins_21272.pdf to invoice_Tracy Hopkins_21272.pdf
(OCR)

Tables
No table found on this page.
(OCR)

Tables
No table found on this page.
(OCR)

Tables
No table found on this page.
(OCR)

Tables
No table found on this page.
(OCR)

Tables
No table found on this page.

In [ ]:
# !unzip /content/fine_tuned_distilbart.zip

Bart model

In [ ]:
def generate_neat_json(ocr_texts):
    model_path = "/content/fine_tuned_distilbart_clean_json"
    model = BartForConditionalGeneration.from_pretrained(model_path)
    tokenizer = AutoTokenizer.from_pretrained(model_path)
    all_Jsons=[]
    for ocr_text in ocr_texts:
      input_ids = tokenizer(ocr_text, return_tensors="pt", max_length=512, truncation=True).input_ids
      output_ids = model.generate(input_ids, num_beams=4, max_length=512, early_stopping=True)
      corrected_json = tokenizer.decode(output_ids[0], skip_special_tokens=True)
      all_Jsons.append(corrected_json)

    return all_Jsons

In [ ]:
all_jsons = generate_neat_json(ocr_texts)
print(all_jsons)

['{"Invoice Number": "# 25880", "Date": "2012-11-17", "Bill To": "Tony Molinari Surabaya", "Ship To": null, "Ship Mode": "First Class", "Balance Due": 1575.82, "Items": [{"Item Name": "Rogers File Cart, Industrial", "Quantity": 4, "Unit Price": 470.11, "Total Price": 1580.45}], "Subtotal": 1540.45, "Discount": 319.68, "Shipping": 199.05, " Total": 1555.82 , "Notes": "Thanks for your business!", "Order ID": "IN-2012-TM2149059-41230"}', '{"Invoice Number": "# 25881", "Date": "2012-11-17", "Bill To": "Tony Molinari Surabaya", "Ship To": null, "Ship Mode": "First Class", "Balance Due": 4368.45, "Items": [{"Item Name": "Novimex Swivel Stool, Black", "Quantity": 7, "Unit Price": 827.97, "Total Price": 54795.81}], "Subtotal": 5475.81, "Discount": 1464.87, "Shipping": 137.51, " Total": 436.45 , "Notes": "Thanks for your business!", "Order ID": "IN-2012-TM2149059-41230"}', '{"Invoice Number": "# 20584", "Date": "2012-10-25", "Bill To": "Tracy Blumstein Pekanbaru", "Ship To": null, "Ship Mode": "Standard Class", "Balance Due": 1556.57, "Items": [{"Item Name": "Breville Refrigerator, Red", "Quantity": 2, "Unit Price": 852.09, "Total Price": 1524.18}], "Subtotal": 15 24.18, "Discount": 293.11, "Shipping": 120.5, " Total":1556. 57, "Notes": "Thanks for your business!", "Order ID": "IN-2012-TB2152059-41207"}', '{"Invoice Number": "# 28215", "Date": "2012-06-23", "Bill To": "Tracy Blumstein Geelong", "Ship To": null, "Ship Mode": "Second Class", "Balance Due": 3365.06, "Items": [{"Item Name": "StarTech Card Printer, White", "Quantity": 5, "Unit Price": 716.6, "Total Price": 3642.98}], "Subtotal": 364.98, "Discount": 364.3, "Shipping": 86.38, " Total": 3 365.06 , "Notes": "Thanks for your business!", "Order ID": "IN-2012-TB215207-41083"}', '{"Invoice Number": "# 21272", "Date": "2012-07-19", "Bill To": "Tracy Hopkins Melbourne", "Ship To": null, "Ship Mode": "First Class", "Balance Due": 580.92, "Items": [{"Item Name": "Hewlett Personal Copier, Color", "Quantity": 2, "Unit Price": 262.28, "Total Price": 524.56}], "Subtotal": 526.56, "Discount": 52.46, "Shipping": 108.82, and "Total": 5580. 92, "Notes": "Thanks for your business!", "Order ID": "IN-2012-TH215507-41109"}']

In [ ]:
def clean_json(json_str):
    # Replace "Na N" and "NaN" with "null"
    json_str = json_str.replace("Na N", "null")
    json_str = json_str.replace("NaN", "null")
    json_str = re.sub(r"(\d+)\s*\.\s*(\d+)", r'\1.\2', json_str)
    json_str = re.sub(r'(\d+)\s+(\d+)', r'\1\2', json_str)
    json_str = re.sub(r'"\s*(\S+)"\s*:', r'"\1":', json_str)  #  spaces before keys
    json_str = re.sub(r'\s+"(\S+)"', r'"\1"', json_str)  #  extra spaces before values
    json_str = re.sub(r'"Ship Mode":\s*"rst Class"', r'"Ship Mode": "First Class"', json_str)
    # Fix possible extra spaces( "Total": 454. 12 "Total": 454.12)
    json_str = re.sub(r'("Total":\s*\d+)\s+(\d)', r'\1\2', json_str)
    json_str = re.sub(r'"Subtotal":\s*null', '"Subtotal": 0', json_str)
    # Remove any invalid "and" keyword
    json_str = re.sub(r"\s*and\s*", "", json_str)
    json_str = re.sub(r'\s+:', ':', json_str)  # space before colon
    json_str = re.sub(r':\s+', ':', json_str)  # space after colon
    json_str = re.sub(r'\s+,', ',', json_str)  #space before commas

    return json_str


def ship_to(all_jsons, ocr_texts):
    # Map invoices by their number for quick reference
    invoice_map = {json.loads(clean_json(js))["Invoice Number"]: json.loads(clean_json(js)) for js in all_jsons}


    for js in all_jsons:
        ocr_text_index = all_jsons.index(js)
        ocr_text = ocr_texts[ocr_text_index]

        ner_results = perform_ner(ocr_text)
        ship_add = ocr_to_json_with_ner(ocr_text, ner_results)
        invoice_number = json.loads(clean_json(js))["Invoice Number"]
        invoice_map[invoice_number]["Ship To"] = ship_add

    return list(invoice_map.values())

chunk_data = ship_to(all_jsons, ocr_texts)

In [ ]:
for chunk in chunk_data:
  print(chunk)

{'Invoice Number': '# 25880', 'Date': '2012-11-17', 'Bill To': 'Tony Molinari Surabaya', 'Ship To': 'Jawa Timur, Indonesia', 'Ship Mode': 'First Class', 'Balance Due': 1575.82, 'Items': [{'Item Name': 'Rogers File Cart, Industrial', 'Quantity': 4, 'Unit Price': 470.11, 'Total Price': 1580.45}], 'Subtotal': 1540.45, 'Discount': 319.68, 'Shipping': 199.05, 'Total': 1555.82, 'Notes': 'Thanks for your business!', 'Order ID': 'IN-2012-TM2149059-41230'}
{'Invoice Number': '# 25881', 'Date': '2012-11-17', 'Bill To': 'Tony Molinari Surabaya', 'Ship To': 'Jawa Timur, Indonesia', 'Ship Mode': 'First Class', 'Balance Due': 4368.45, 'Items': [{'Item Name': 'Novimex Swivel Stool, Black', 'Quantity': 7, 'Unit Price': 827.97, 'Total Price': 54795.81}], 'Subtotal': 5475.81, 'Discount': 1464.87, 'Shipping': 137.51, 'Total': 436.45, 'Notes': 'Thanks for your business!', 'Order ID': 'IN-2012-TM2149059-41230'}
{'Invoice Number': '# 20584', 'Date': '2012-10-25', 'Bill To': 'Tracy Blumstein Pekanbaru', 'Ship To': 'Riau, Indonesia', 'Ship Mode': 'Stard Class', 'Balance Due': 1556.57, 'Items': [{'Item Name': 'Breville Refrigerator, Red', 'Quantity': 2, 'Unit Price': 852.09, 'Total Price': 1524.18}], 'Subtotal': 1524.18, 'Discount': 293.11, 'Shipping': 120.5, 'Total': 1556.57, 'Notes': 'Thanks for your business!', 'Order ID': 'IN-2012-TB2152059-41207'}
{'Invoice Number': '# 28215', 'Date': '2012-06-23', 'Bill To': 'Tracy Blumstein Geelong', 'Ship To': 'Victoria, Australia', 'Ship Mode': 'Second Class', 'Balance Due': 3365.06, 'Items': [{'Item Name': 'StarTech Card Printer, White', 'Quantity': 5, 'Unit Price': 716.6, 'Total Price': 3642.98}], 'Subtotal': 364.98, 'Discount': 364.3, 'Shipping': 86.38, 'Total': 3365.06, 'Notes': 'Thanks for your business!', 'Order ID': 'IN-2012-TB215207-41083'}
{'Invoice Number': '# 21272', 'Date': '2012-07-19', 'Bill To': 'Tracy Hopkins Melbourne', 'Ship To': 'Victoria, Australia', 'Ship Mode': 'First Class', 'Balance Due': 580.92, 'Items': [{'Item Name': 'Hewlett Personal Copier, Color', 'Quantity': 2, 'Unit Price': 262.28, 'Total Price': 524.56}], 'Subtotal': 526.56, 'Discount': 52.46, 'Shipping': 108.82, 'Total': 5580.92, 'Notes': 'Thanks for your business!', 'Order ID': 'IN-2012-TH215507-41109'}

Question answering model

In [ ]:
# from transformers import pipeline

# qa_pipeline = pipeline("question-answering", model="distilbert-base-cased-distilled-squad", tokenizer="distilbert-base-cased")

# # Define the question
# question = "What is the total balance due?"

# # Use the QA model to get the answer
# result = qa_pipeline(question=question, context=json_output)

# # Output the answer
# print(f"Answer: {result['answer']}")

In [ ]:
# # Ask the user for the number of questions
# num_questions = int(input("How many questions would you like to ask? "))

# # Initialize an empty list to store user-input questions
# questions = []

# # Take user input for each question
# for _ in range(num_questions):
#     question = input("Please enter your question: ")
#     questions.append(question)

# # Iterate through the list of questions and get answers
# for question in questions:
#     result = qa_pipeline(question=question, context=json_output)

#     # Output the answer for each question
#     print(f"Question: {question}")
#     print(f"Answer: {result['answer']}")
#     print("-" * 50)  # Separator between answers

finetuning google/flant5 for 6 epoch

In [ ]:
# import pandas as pd
# from datasets import Dataset
# from transformers import T5ForConditionalGeneration, T5Tokenizer, TrainingArguments, Trainer

# # Load data
# df = pd.read_csv("/content/cleaned_ocr_json_output.csv").head(700)

# def format_data(row):
#     return {
#         "input_text": f"OCR text: {row['OCR_Text']}\nGenerate JSON:",
#         "target_text": row['JSON_Text']
#     }

# formatted_data = pd.DataFrame(df.apply(format_data, axis=1).tolist())
# dataset = Dataset.from_pandas(formatted_data)

# # Split dataset
# dataset = dataset.train_test_split(test_size=0.1)

# # Load T5 model and tokenizer
# model_name = "google/flan-t5-small"
# model = T5ForConditionalGeneration.from_pretrained(model_name)
# tokenizer = T5Tokenizer.from_pretrained(model_name)

# # Preprocess data
# def preprocess_function(examples):
#     model_inputs = tokenizer(examples["input_text"], max_length=512, truncation=True, padding="max_length")
#     labels = tokenizer(examples["target_text"], max_length=256, truncation=True, padding="max_length")
#     model_inputs["labels"] = labels["input_ids"]
#     return model_inputs

# tokenized_datasets = dataset.map(preprocess_function, batched=True)

# # Training arguments
# training_args = TrainingArguments(
#     output_dir="./results",
#     evaluation_strategy="epoch",
#     learning_rate=1e-5,
#     per_device_train_batch_size=4,
#     per_device_eval_batch_size=4,
#     num_train_epochs=6,
#     weight_decay=0.01,
#     save_strategy="epoch",
#     report_to="none" ,
#     push_to_hub=False
# )

# # Trainer setup
# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=tokenized_datasets["train"],
#     eval_dataset=tokenized_datasets["test"]
# )

# # Fine-tune the model
# trainer.train()

# # Save model
# model.save_pretrained("./fine_tuned_t5")
# tokenizer.save_pretrained("./fine_tuned_t5")

model.safetensors:  75%|#######4  | 231M/308M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

Map:   0%|          | 0/630 [00:00<?, ? examples/s]

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.48.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

('./fine_tuned_t5/tokenizer_config.json',
 './fine_tuned_t5/special_tokens_map.json',
 './fine_tuned_t5/spiece.model',
 './fine_tuned_t5/added_tokens.json')

In [ ]:
# from google.colab import files
# !zip -r fine_tuned_t5.zip fine_tuned_t5
# files.download('fine_tuned_t5.zip')

Testing t5

In [ ]:
ocr_text="""
--- Page 1 --- Superstore INVOICE # 23962 Date: Aug 07 2012 Bill To: Ship To: Shio Mode: 5 D Barbara Fisher Guangzhou, ip mone: ame wey Guangdong, China Balance Due: $5,307.27 Item | Quantity Bcc) Amount Canon Fax Machine, Laser 4 $1,273.56 $5,094.24 Copiers, Technology, TEC-CO-3689 Subtotal: $5,094.24 Shipping: $213.03 Total: $5,307.27 Notes: Thanks for your business! Terms: Order ID : IN-2012-BF1097527-41128

"""

In [ ]:
from transformers import T5ForConditionalGeneration, T5Tokenizer

# Load the fine-tuned model
model = T5ForConditionalGeneration.from_pretrained("/content/fine_tuned_t5")
tokenizer = T5Tokenizer.from_pretrained("/content/fine_tuned_t5")


def predict(ocr_text):
    prompt = f"OCR text: {ocr_text}\Extract structured data (in JSON format):"
    inputs = tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)
    outputs = model.generate(**inputs, max_length=256, num_return_sequences=1)
    return json.dumps(tokenizer.decode(outputs[0], skip_special_tokens=True))

In [ ]:
json_op= predict(ocr_text)

In [ ]:
json_op

'"\\"invoice\\":  \\"invoice_number\\": \\"# 23962\\", \\"date\\": \\"2012-07-07\\", \\"bill_to\\": \\"Baby Fisher Guangzhou\\", \\"ship_to\\": \\"Mirandum\\": \\"5 D\\", \\"ship_to\\": \\"Mirandum\\", \\"balance_due\\": $5,307.27, \\"items\\": [  \\"item_name\\": \\"AmountnCanadian Fax Machine, Laser 4\\", \\"quantity\\": 4, \\"unit_price\\": $5,094.24, \\"total_price\\": $5,094.24, \\"shipping\\": $213.03, \\"total\\": $5,307.27, \\"notes\\": \\"Thanks for your business!\\", \\"terms\\":  \\"order_id\\": \\"IN-2012-BF1097527-41128\\""'

In [ ]:
json_data = json.dumps({"invoice": str(json_op)}, indent=4)
print(json_data)

{
    "invoice": "\"invoice\":  \"invoice_number\": \"# 23962\", \"date\": \"2012-07-07\", \"bill_to\": \"Baby Fisher Guangzhou\", \"ship_to\": \"Mirandum\": \"5 D\", \"ship_to\": \"Mirandum\", \"balance_due\": $5,307.27, \"items\": [  \"item_name\": \"AmountnCanadian Fax Machine, Laser 4\", \"quantity\": 4, \"unit_price\": $5,094.24, \"total_price\": $5,094.24, \"shipping\": $213.03, \"total\": $5,307.27, \"notes\": \"Thanks for your business!\", \"terms\":  \"order_id\": \"IN-2012-BF1097527-41128\""
}

In [ ]:
json_op

'"\\"invoice\\":  \\"invoice_number\\": \\"# 23962\\", \\"date\\": \\"2012-07-07\\", \\"bill_to\\": \\"Baby Fisher Guangzhou\\", \\"ship_to\\": \\"Mirandum\\": \\"5 D\\", \\"ship_to\\": \\"Mirandum\\", \\"balance_due\\": $5,307.27, \\"items\\": [  \\"item_name\\": \\"AmountnCanadian Fax Machine, Laser 4\\", \\"quantity\\": 4, \\"unit_price\\": $5,094.24, \\"total_price\\": $5,094.24, \\"shipping\\": $213.03, \\"total\\": $5,307.27, \\"notes\\": \\"Thanks for your business!\\", \\"terms\\":  \\"order_id\\": \\"IN-2012-BF1097527-41128\\""'

sentence bert for cleaning

In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"

import pandas as pd
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader
from sentence_transformers import SentencesDataset

# Load your CSV data
df = pd.read_csv('/content/cleaned_ocr_json_output.csv')
df = df.head(800)


train_data = []


for _, row in df.iterrows():
    raw_text = row['OCR_Text']
    json_text = row['JSON_Text']
    train_data.append(InputExample(texts=[raw_text, json_text]))


train_dataset = SentencesDataset(train_data, SentenceTransformer('all-MiniLM-L6-v2'))
train_dataloader = DataLoader(train_dataset, batch_size=16)


train_loss = losses.MultipleNegativesRankingLoss(model=SentenceTransformer('all-MiniLM-L6-v2'))
model = SentenceTransformer('all-MiniLM-L6-v2')
model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=5, warmup_steps=100)


model.save('/content/fine_tuned_sentence_bert')

# # Example usage: Check similarity after fine-tuning
# raw_text = "Invoice number 40737, dated May 24, 2012. The total balance due is $30.55."
# json_text = '{"invoice_number": "#40737", "date": "2012-May-24", "balance_due": 30.55}'

# raw_text_embedding = model.encode(raw_text, convert_to_tensor=True)
# json_text_embedding = model.encode(json_text, convert_to_tensor=True)

# cosine_similarity = util.pytorch_cos_sim(raw_text_embedding, json_text_embedding)
# print(f"Cosine Similarity after fine-tuning: {cosine_similarity.item()}")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

Training SmolLM model on dataset

In [ ]:
# import pandas as pd
# from datasets import Dataset
# from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer

# # Load and format data
# df = pd.read_csv("/content/cleaned_ocr_json_output.csv").head(700)

# def format_data(row):
#     return {
#         "input_text": f"OCR text: {row['OCR_Text']} Generate JSON:",
#         "target_text": row['JSON_Text']
#     }

# formatted_data = pd.DataFrame(df.apply(format_data, axis=1).tolist())
# dataset = Dataset.from_pandas(formatted_data).train_test_split(test_size=0.1)

# # Load `SmolLM-135M`
# model_name = "HuggingFaceTB/SmolLM-135M"
# model = AutoModelForCausalLM.from_pretrained(model_name)
# tokenizer = AutoTokenizer.from_pretrained(model_name)

# # Set the pad_token to eos_token if it's not defined
# if tokenizer.pad_token is None:
#     tokenizer.pad_token = tokenizer.eos_token

# # Preprocess function to tokenize inputs and labels
# def preprocess_function(examples):
#     # Tokenize the input text (OCR text)
#     model_inputs = tokenizer(examples["input_text"], max_length=512, truncation=True, padding="max_length")

#     # Tokenize the target text (JSON text)
#     labels = tokenizer(examples["target_text"], max_length=512, truncation=True, padding="max_length")

#     # Ensure that labels are the same length as input
#     model_inputs["labels"] = labels["input_ids"]

#     # Replace padding tokens in labels with -100 to ignore during loss computation
#     model_inputs["labels"] = [
#         (label if label != tokenizer.pad_token_id else -100)
#         for label in model_inputs["labels"]
#     ]

#     return model_inputs

# # Tokenize dataset
# tokenized_datasets = dataset.map(preprocess_function, batched=True)

# # Training arguments
# training_args = TrainingArguments(
#     output_dir="./results",
#     evaluation_strategy="epoch",
#     learning_rate=1e-5,
#     per_device_train_batch_size=4,  # Adjusted batch size
#     per_device_eval_batch_size=4,   # Adjusted batch size
#     num_train_epochs=6,
#     weight_decay=0.01,
#     save_strategy="epoch",
#     report_to="none",
#     push_to_hub=False
# )

# # Trainer setup
# trainer = Trainer(
#     model=model,
#     args=training_args,
#     train_dataset=tokenized_datasets["train"],
#     eval_dataset=tokenized_datasets["test"]
# )

# # Fine-tune the model
# trainer.train()

# # Save model
# model.save_pretrained("./fine_tuned_smolLM6ep")
# tokenizer.save_pretrained("./fine_tuned_smolLM6ep")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/724 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/538M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/3.69k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/801k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/466k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.10M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/831 [00:00<?, ?B/s]

Map:   0%|          | 0/630 [00:00<?, ? examples/s]

Map:   0%|          | 0/70 [00:00<?, ? examples/s]

/usr/local/lib/python3.11/dist-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

('./fine_tuned_smolLM6ep/tokenizer_config.json',
 './fine_tuned_smolLM6ep/special_tokens_map.json',
 './fine_tuned_smolLM6ep/vocab.json',
 './fine_tuned_smolLM6ep/merges.txt',
 './fine_tuned_smolLM6ep/added_tokens.json',
 './fine_tuned_smolLM6ep/tokenizer.json')

In [ ]:
ocr_text="""
-- Page 1 --- Superstore INVOICE # 19009 Date: Jan 04 2013 Bill To: Ship To: Shio Mode: Standard Cl Deanra Eno Paris, Ile-de-France, ip mone: andare ass France Balance Due: $4,095.17 Item | Quantity Btcltc) Amount Smead Lockers, Single Width 5 $893.03 $4,465.13 Storage, Office Supplies, OFF-ST-6048 Subtotal: $4,465.13 Discount (10%): $446.51 Shipping: $76.55 Total: $4,095.17 Notes: Thanks for your business! Terms: Order ID : ES-2013-DE1325545-41278
"""